### ISSUE TITLE
Code Design

### ISSUE THREAD

**Issue by Eldritch-Oliver** [Oliver-Akins/Phantom-Ink-Online#3]
Front end:
 - Vue.js (written in Typescript, compiled to an SPA)
 - Socket.io (https://socket.io)

Back end:
 - Node 10.19.0
 - Typescript 3.8.3
 - Configuration file: TOML (see example config below)
 - Any value in the server config file would require a full server restart for the changes to take effect.
 - All the Google Sheets would be fetched for each game uniquely, which would allow almost-live editing.
 - The two types of data formats available for cards is `csv`, and `sheets`, CSV files would be stored on the server, sheets uses Google Sheets to store the data and then fetches it from it.
 - Written in TypeScript, trans-compiled to JavaScript for running.
 - Socket.io (https://socket.io)
 - Express.js (https://expressjs.com) for serving the compiled SPA and any additional assets as needed.

Example Configuration:
```toml
[cards]
type = "sheets" # or "csv"

# The Google sheets key for the document if the type is "sheets"
key = ''

# The file path to the CSV (absolute from the assets directory) or Google ID of the specific sheet
questions = ''
objects = ''
eyes = ''


# The name and icon for team 1
[team_1]
name = ""
icon = ''

# The name and icon for team 2
[team_2]
name = ""
icon = ''


# The settings relating to how the web server functions
[webserver]
port = 3030
code_length = 2


# General settings for the game
[game]
writer_name = "Spectre"
guesser_name = "Medium"
```
